platform :ios,'8.0'
xcodeproj 'ChatDemo.xcodeproj'
target 'ChatDemo' do
    pod 'AFNetworking', '~> 3.1.0'
    pod 'RongCloudIM/IMLib', '~> 2.8.3'
    pod 'KC_Encryption', '~> 1.0'
    pod 'ShareSDK3'
    pod 'MOBFoundation'
    pod 'ShareSDK3/ShareSDKPlatforms/QQ'
    pod "Qiniu", "~> 7.1"
    pod 'SDWebImage', '~> 4.0.0'
    pod 'MJRefresh', '~> 3.1.12'
pod 'LFLiveKit'

end
